# Generated by Django 2.2.4 on 2020-12-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pub_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='item',
            name='expo',
            field=models.TextField(blank=True, default='燻製', null=True),
        ),
    ]
